name: Run solver
on:
  workflow_dispatch:
jobs:
  run-solver:
    permissions:
      contents: write
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - name: Build and run solver
        run: |
          zig build solve -Doptimize=ReleaseFast

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update solver output files
          branch: ${{ github.head_ref }}
